server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route # 搜索工程路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route # 搜索工程路由  同步请求
          uri: lb://index-service
          predicates:
            - Host=gmall.com, www.gmall.com
        - id: index-route2 # 搜索工程路由   异步请求
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route # 商品详情页路由
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
