server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.34.3:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_pms
    username: root
    password: 123456
  sleuth: #采集率
    sampler:
      probability: 1
  redis:
    host: 101.200.34.3
    port: 9379
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.atguigu.gmall.pms.entity